version: '3'

services:
  mockServer:
    image: jamesdbloom/mockserver:latest
    ports:
      - 1080:1080
    environment:
      - LOG_LEVEL=INFO
  
  queueServer:
    image: rabbitmq:latest
    ports:
      - 1082:5672

  command-acceptor:
    build: ..\command-acceptor
    command: python run.py
    ports:
      - 1081:8080
    depends_on:
      - queueServer