version: '3'

services:
  mock-server:
    image: jamesdbloom/mockserver:latest
    ports:
      - "1080:1080"
    environment:
      - LOG_LEVEL=INFO

  mysql-server:
    image: mysql:5
    container_name: test-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: "badmessages"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./mysql-init:/docker-entrypoint-initdb.d/:ro"

  queue-server: # guest:guest
    image: rabbitmq:management
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  command-acceptor:
    build: ../command-acceptor
    command: python run.py
    ports:
      - "1081:8080"
    depends_on:
      - queue-server

  telegram-pusher:
    build: ../telegram-pusher
    command: python run.py -d /cfg -e dev
    restart: on-failure
    links:
      - queue-server
      - mysql-server
      - mock-server
    depends_on:
      - mock-server
      - queue-server
      - mysql-server